//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char enemy2 [] = {
0xFF, 0x89, 0x9D, 0xDD, 0xDD, 0x9D, 0x89, 0xFF, 
};
