//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char enemy1 [] = {
0x3C, 0x66, 0xCF, 0x9F, 0x9F, 0xCF, 0x66, 0x3C, 
};
