//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char ship [] = {
0x30, 0xDC, 0x4C, 0xF7, 0xF7, 0x5C, 0xCC, 0x70, 
};
